### ISSUE TITLE
Collecting metadata / telemetry

### ISSUE THREAD

**Issue by jallard-007** [jallard-007/git-cache-clone#2]
Support collecting metadata #1 per run

Include metrics on the individual action that was done, as well as any relevant totals/avgs.

Configured to call external apis; just provide the data, no need to do more

configuration:
```toml
[metrics]
backend = "script:./scripts/export_metrics.sh"
# or:
backend = "python:custom_exporter.push_to_prometheus"
# or:
backend = "http:https://my-server.com/metrics"
```

example payload:
```json
{
  "host": "hostname",
  "timestamp": "time",
  "clone_uri": "uri",
  "in_cache": true,
  "clone_time_sec": 12.3,
  "total_hits": 100,
  "avg_clone_time_sec": 10.2,
}
```
